library(nmR)
setwd("~/GitSoftware/global_quality_assessment/reference_errors//")
expnames <- c("resname","resid","nucleus","expCS","error")
prednames <- c("model","resid","resname","nucleus","predCS","id")
rnas <- unlist(strsplit("1KKA 1L1W 1LC6 1LDZ 1NC0 1OW9 1PJY 1R7W 1SCL 1UUU 1XHP 1YSV 1Z2J 1ZC5 2FDT 2JWV 2K66 2KOC 2L3E 2LBJ 2LBL 2LDL 2LDT 2LHP 2LI4 2LK3 2LP9 2LPA 2LQZ 2LU0 2LUB 2LUN 2LV0 2M12 2M21 2M22 2M24 2M4W 2M5U 2M8K 2MEQ 2MFD 2MHI 2MNC 2MXL 2N2O 2N2P 2N4L 2N6S 2N6T 2N6W 2N6X 2NCI 2QH2 2QH4 2Y95 4A4S 4A4T 4A4U 5A17 5A18 5KQE"," "))
for (rna in rnas){
  expcs <- read.table(paste("/Users/atfrank/Documents/GitSoftware/global_quality_assessment/reference_errors/",rna,"/chemical_shifts.txt.gz",sep=""), col.names = expnames, stringsAsFactors = FALSE)
  predcs_larmord <- read.table(paste("/Users/atfrank/Documents/GitSoftware/global_quality_assessment/reference_errors/",rna,"/chemical_shifts.larmord.txt.gz",sep=""), col.names = prednames, stringsAsFactors = FALSE)
  predcs_ramsey <- read.table(paste("/Users/atfrank/Documents/GitSoftware/global_quality_assessment/reference_errors/",rna,"/chemical_shifts.ramsey.txt.gz",sep=""), col.names = prednames, stringsAsFactors = FALSE)
  reference <- detect_referencing_error(expcs, predcs_larmord, verbose = FALSE)  
  save(reference, file=paste("/Users/atfrank/Documents/GitSoftware/global_quality_assessment/reference_errors/",rna,"/referencing_errors_larmord.RData",sep=""))
  reference <- detect_referencing_error(expcs, predcs_ramsey, verbose = FALSE)  
  save(reference, file=paste("/Users/atfrank/Documents/GitSoftware/global_quality_assessment/reference_errors/",rna,"/referencing_errors_ramsey.RData",sep=""))
  cat(sprintf("done with %s\n",rna))
}
