#!/bin/bash
source ~/.bashrc 

PDB=$1

models=`grep MODEL coors/${PDB}.pdb | wc -l | awk '{print $1}'`
models=`seq 1 $models`

# Create sequence of model numbers

rm -rf data/larmord_${PDB}.txt data/ramsey_${PDB}.txt
# Loop over models and write out individual PDBs
for i in $models
do
	 f=coors/${PDB}_${i}.pdb
	 echo "convpdb.pl -model $i coors/${PDB}.pdb | grep ATOM > coors/${PDB}_${i}.pdb" | bash
	 ${LarmorD}/bin/larmord -parmfile ${LarmorD}//data/larmorD_alphas_betas_rna.dat -reffile ${LarmorD}/data/larmorD_reference_shifts_rna.dat -accfile ${LarmorD}/data/larmorD_accuracy_weight_rna.dat -cutoff 9999.0 ${f} | awk -v model=$i -v id=$f '{print model, $3, $4, $5, $6, id}' | tee -a data/larmord_${PDB}.txt
	 curl --fail --silent -X POST -F pdb=@$f http://50.63.157.7/RAMSEYWebService/upload/  | sed 's/<.*>//g' | awk -v model=$i -v id=$f '{ if (NF>3) print model, $3, $1, $4, $5, id}' | sed 's/URI/URA/g'  | awk '{if(NF==6) print}' | tee -a data/ramsey_${PDB}.txt      
done
