#!/bin/bash
source ~/.bashrc 

PDB1=$1
PDB2=$2
PDB=`echo ${PDB1}_${PDB2}`

rm -rf data/larmord_${PDB}_average.txt data/ramsey_${PDB}_average.txt

# Loop over models and write out individual PDBs
i=1
f=coors/${PDB1}_ave_min.pdb
${LarmorD}/bin/larmord -parmfile ${LarmorD}//data/larmorD_alphas_betas_rna.dat -reffile ${LarmorD}/data/larmorD_reference_shifts_rna.dat -accfile ${LarmorD}/data/larmorD_accuracy_weight_rna.dat -cutoff 9999.0 ${f} | awk -v model=$i -v id=$f '{print model, $3, $4, $5, $6, id}' | tee -a data/larmord_${PDB}_average.txt
curl --fail --silent -X POST -F pdb=@$f http://50.63.157.7/RAMSEYWebService/upload/  | sed 's/<.*>//g' | awk -v model=$i -v id=$f '{ if (NF>3) print model, $3, $1, $4, $5, id}' | sed 's/URI/URA/g'  | awk '{if(NF==6) print}' | tee -a data/ramsey_${PDB}_average.txt      

i=2
f=coors/${PDB2}_ave_min.pdb
${LarmorD}/bin/larmord -parmfile ${LarmorD}//data/larmorD_alphas_betas_rna.dat -reffile ${LarmorD}/data/larmorD_reference_shifts_rna.dat -accfile ${LarmorD}/data/larmorD_accuracy_weight_rna.dat -cutoff 9999.0 ${f} | awk -v model=$i -v id=$f '{print model, $3, $4, $5, $6, id}' | tee -a data/larmord_${PDB}_average.txt
curl --fail --silent -X POST -F pdb=@$f http://50.63.157.7/RAMSEYWebService/upload/  | sed 's/<.*>//g' | awk -v model=$i -v id=$f '{ if (NF>3) print model, $3, $1, $4, $5, id}' | sed 's/URI/URA/g'  | awk '{if(NF==6) print}' | tee -a data/ramsey_${PDB}_average.txt      
